export const STRINGS = {
  "ko-KR": {
    moodTopLabel: "오늘의 기분",
    next: "다음",
    prev: "이전",
    viewResult: "결과 보기",
    whereToWatch: "어디에서 볼까요?",
    whereToWatchDesc:
      "지금 가입해 둔 OTT를 선택하면,\n그 안에서 볼 수 있는 작품만 골라 드릴게요.",
    recommendLineSuffix: " 기분에 맞는 작품을 추천했어요.",
    moodReset: "Change mood",
    ottReset: "Change ott",
    settings: "설정",
    favoritesTitle: "내가 저장한 작품",
    loading: "추천 작품을 불러오는 중입니다...",
    notFound: "조건에 맞는 작품을 찾지 못했어요.",
    noOverview: "줄거리 정보가 없습니다.",
    yearNA: "연도 정보 없음",
    trailerNotFound: "예고편을 찾지 못했어요.",
    trailerOpenFail: "예고편 링크를 여는 중 문제가 발생했어요.",
    youtubeTrailer: "▶ YouTube 예고편",
    close: "닫기",
    baseInfo: "기본 정보",
    releaseDate: "개봉일",
    rating: "평점",
    overview: "줄거리",
    infoNA: "정보 없음",
    favoriteOn: "★ 즐겨찾기",
    favoriteOff: "☆ 즐겨찾기",
    pickLang: "언어",
    pickRegion: "지역",
    regionKR: "KR",
    regionUS: "US",
    save: "저장",
  },
  "en-US": {
    moodTopLabel: "Today's Mood",
    next: "Next",
    prev: "Back",
    viewResult: "See results",
    whereToWatch: "Where will you watch?",
    whereToWatchDesc:
      "Pick a streaming service you use,\nthen I'll recommend titles available there.",
    recommendLineSuffix: " mood recommendations.",
    moodReset: "Change mood",
    ottReset: "Change ott",
    settings: "Settings",
    favoritesTitle: "Saved titles",
    loading: "Loading recommendations...",
    notFound: "No titles found for these filters.",
    noOverview: "No overview available.",
    yearNA: "Year N/A",
    trailerNotFound: "No trailer found.",
    trailerOpenFail: "Could not open the trailer link.",
    youtubeTrailer: "▶ YouTube Trailer",
    close: "Close",
    baseInfo: "Info",
    releaseDate: "Release date",
    rating: "Rating",
    overview: "Overview",
    infoNA: "N/A",
    favoriteOn: "★ Saved",
    favoriteOff: "☆ Save",
    pickLang: "Language",
    pickRegion: "Region",
    regionKR: "KR",
    regionUS: "US",
    save: "Save",
  },
};

export const t = (lang, key) =>
  STRINGS[lang]?.[key] ?? STRINGS["en-US"][key] ?? key;
