import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screenRoot: { flex: 1, backgroundColor: "#050816" },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#F9FAFB",
    marginBottom: 12,
  },
  smallText: { fontSize: 13, color: "#9CA3AF" },
  centerFill: { flex: 1, alignItems: "center", justifyContent: "center" },

  // Mood
  moodScreenContainer: { flex: 1, paddingHorizontal: 20 },
  moodTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  moodTopLabel: { fontSize: 13, color: "#9CA3AF" },
  moodTopStep: { fontSize: 12, color: "#6B7280", marginLeft: 10 },
  moodQuestionBlock: { marginBottom: 32 },
  moodQuestionText: {
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "700",
    color: "#F9FAFB",
  },
  moodOptionsBlock: { flexGrow: 1 },
  moodOptionButton: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#1F2933",
    backgroundColor: "#0B1120",
    marginBottom: 12,
  },
  moodOptionButtonSelected: {
    borderColor: "#3B82F6",
    backgroundColor: "#1D4ED8",
  },
  moodOptionText: { fontSize: 15, color: "#E5E7EB" },
  moodOptionTextSelected: { color: "#F9FAFB", fontWeight: "600" },
  moodErrorText: { color: "#FCA5A5", fontSize: 12, marginTop: 12 },
  moodBottomRow: { flexDirection: "row", alignItems: "center", marginTop: 24 },
  moodPrevButton: { paddingVertical: 10, paddingHorizontal: 10 },
  moodPrevText: { fontSize: 14, color: "#9CA3AF" },
  moodNextButton: {
    flex: 1,
    marginLeft: 8,
    paddingVertical: 13,
    borderRadius: 999,
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
  },
  moodNextText: { fontSize: 15, fontWeight: "600", color: "#020617" },

  moodHighlight: { color: "#4ade80", fontWeight: "600" },

  // Ott select
  ottScreenContainer: { flex: 1, paddingHorizontal: 20 },
  ottDescriptionText: { fontSize: 14, color: "#9CA3AF", marginBottom: 20 },
  ottList: { paddingBottom: 16 },
  ottItemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
    backgroundColor: "#0B1120",
    marginBottom: 10,
  },
  ottLogoImage: { width: 40, height: 40, borderRadius: 8, marginRight: 12 },
  ottNameText: { fontSize: 16, fontWeight: "500", color: "#F9FAFB" },
  ottItemSelected: {
    borderWidth: 1,
    borderColor: "#3B82F6",
    backgroundColor: "#111827",
  },

  // Results
  resultScreenContainer: { flex: 1, paddingHorizontal: 16 },
  resultHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  resultMoodRight: { flexDirection: "row", alignItems: "center" },
  resultMoodResetButton: {
    marginLeft: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: "#111827",
  },
  resultMoodResetText: { fontSize: 12, color: "#9CA3AF" },

  movieCard: {
    flexDirection: "row",
    borderRadius: 16,
    backgroundColor: "#0B1120",
    marginBottom: 12,
    overflow: "hidden",
    position: "relative",
  },
  movieCardWithTrailer: { borderWidth: 1, borderColor: "#EF4444" },
  moviePosterWrapper: { width: 90, height: 130, backgroundColor: "#111827" },
  moviePosterImage: { width: "100%", height: "100%" },
  movieInfoArea: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    justifyContent: "space-between",
  },
  movieTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#F9FAFB",
    marginBottom: 4,
  },
  movieMetaText: { fontSize: 12, color: "#9CA3AF", marginBottom: 4 },
  movieOverviewText: { fontSize: 12, color: "#6B7280", marginBottom: 8 },

  cardBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  favoriteButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: "#111827",
  },
  favoriteButtonText: { fontSize: 12, color: "#FBBF24" },

  trailerButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "#FF0000",
    alignItems: "center",
    justifyContent: "center",
  },
  trailerButtonText: { fontSize: 12, fontWeight: "600", color: "#F9FAFB" },

  favoritesSection: { marginTop: 16, marginBottom: 8 },
  favoritesListHorizontal: { paddingVertical: 4 },
  favoriteSmallCard: { width: 90, marginRight: 8 },
  favoriteSmallPoster: {
    width: 90,
    height: 130,
    borderRadius: 10,
    backgroundColor: "#111827",
  },
  favoriteSmallTitle: { marginTop: 4, fontSize: 11, color: "#E5E7EB" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalContent: {
    maxHeight: "80%",
    borderRadius: 20,
    backgroundColor: "#020617",
    padding: 16,
  },
  modalHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#F9FAFB",
    flex: 1,
    marginRight: 8,
  },
  modalCloseButton: { paddingHorizontal: 6, paddingVertical: 4 },
  modalCloseText: { fontSize: 14, color: "#9CA3AF" },
  modalBodyScroll: { marginTop: 8 },
  modalSectionTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#E5E7EB",
    marginTop: 10,
    marginBottom: 4,
  },
  modalText: { fontSize: 12, color: "#9CA3AF", lineHeight: 18 },
  modalTrailerButton: {
    marginTop: 12,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#FF0000",
    alignItems: "center",
    justifyContent: "center",
  },
  modalTrailerButtonText: { fontSize: 14, fontWeight: "600", color: "#F9FAFB" },

  youtubeBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FF0000",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  youtubeBadgeText: { color: "#F9FAFB", fontSize: 12, fontWeight: "700" },
});
